apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"playground"},"name":"playground","namespace":"dev"},"spec":{"ports":[{"port":8888,"targetPort":8888}],"selector":{"app":"playground"}}}
  creationTimestamp: "2024-05-22T08:03:45Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: playground
  name: playground
  namespace: dev
  resourceVersion: "9411"
  uid: c4cd9cc2-f766-4d6c-a333-602ed576ebae
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.149.67
  clusterIPs:
  - 10.43.149.67
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31882
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: playground
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.21.0.2
    - ip: 172.21.0.4
